using System;
using System.IO;
using System.Text;
class Program {
    static uint R32(BinaryReader br,int o){ br.BaseStream.Seek(o,SeekOrigin.Begin); return br.ReadUInt32(); }
    static ushort R16(BinaryReader br,int o){ br.BaseStream.Seek(o,SeekOrigin.Begin); return br.ReadUInt16(); }
    static string RS(BinaryReader br,int o){ br.BaseStream.Seek(o,SeekOrigin.Begin); var bytes=new System.Collections.Generic.List<byte>(); byte b; while((b=br.ReadByte())!=0) bytes.Add(b); return Encoding.ASCII.GetString(bytes.ToArray()); }
    static int Main(string[] args){ using var br=new BinaryReader(File.OpenRead(args[0])); if(br.ReadUInt16()!=0x5A4D) return 1; int pe=(int)R32(br,0x3C); br.BaseStream.Seek(pe,SeekOrigin.Begin); if(br.ReadUInt32()!=0x4550) return 2; ushort sections=R16(br,pe+6); ushort opt=R16(br,pe+20); int optOff=pe+24; ushort magic=R16(br,optOff); int ddOff=optOff+(magic==0x20b?112:96); uint exportRva=R32(br,ddOff); uint exportSize=R32(br,ddOff+4); int secOff=optOff+opt; uint expFile=0; for(int i=0;i<sections;i++){ int s=secOff+i*40; uint va=R32(br,s+12); uint raw=R32(br,s+20); uint rawSize=R32(br,s+16); uint virtSize=R32(br,s+8); uint size=Math.Max(rawSize,virtSize); if(exportRva>=va && exportRva<va+size){ expFile=raw+(exportRva-va); break; } } if(expFile==0) return 3; uint numNames=R32(br,(int)expFile+24); uint namesRva=R32(br,(int)expFile+32); uint namesFile=0; for(int i=0;i<sections;i++){ int s=secOff+i*40; uint va=R32(br,s+12); uint raw=R32(br,s+20); uint rawSize=R32(br,s+16); uint virtSize=R32(br,s+8); uint size=Math.Max(rawSize,virtSize); if(namesRva>=va && namesRva<va+size){ namesFile=raw+(namesRva-va); break; } } for(uint i=0;i<numNames;i++){ uint nameRva=R32(br,(int)namesFile+(int)(i*4)); uint nameFile=0; for(int j=0;j<sections;j++){ int s=secOff+j*40; uint va=R32(br,s+12); uint raw=R32(br,s+20); uint rawSize=R32(br,s+16); uint virtSize=R32(br,s+8); uint size=Math.Max(rawSize,virtSize); if(nameRva>=va && nameRva<va+size){ nameFile=raw+(nameRva-va); break; } } Console.WriteLine(RS(br,(int)nameFile)); } return 0; }
}
